DROP TABLE CLUSTER;

CREATE TABLE CLUSTER (
ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
NAME VARCHAR2(255) DEFAULT NULL,
NUMBER NUMBER(10, 0) DEFAULT NULL,
PRIMARY KEY (ID));

DROP SEQUENCE CLUSTER_ID_SEQ;

CREATE SEQUENCE CLUSTER_ID_SEQ
  MINVALUE 1
  MAXVALUE 9999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 100;